services:
  app:
    container_name: cr-app
    build: .
    environment:
      TZ: $TIME_ZONE
      APP_HTTP_PORT: $APP_HTTP_PORT
      APP_NAME: $APP_NAME
      APP_PREFORK: $APP_PREFORK
      APP_CASE_SENSITIVE: $APP_CASE_SENSITIVE
      APP_STRICT_ROUTING: $APP_STRICT_ROUTING
      APP_SERVER_HEADER: $APP_SERVER_HEADER
      DB_HOST: cr-db
      DB_PORT: 5432
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
      DB_SSL_MODE: disable
      REDIS_HOST: cr-redis
      REDIS_PORT: $REDIS_DOCKER_PORT
      REDIS_PASS: $REDIS_PASS
      REDIS_DB: 0
      REDIS_TTL: $REDIS_TTL
    ports:
      - $APP_HTTP_PORT:$APP_HTTP_PORT
    depends_on:
      - postgres
      - redis
    restart: always

  redis:
    container_name: cr-redis
    image: redis:latest
    environment:
      TZ: $TIME_ZONE
    entrypoint: redis-server --requirepass $REDIS_PASS --maxmemory 512mb --maxmemory-policy allkeys-lru
    ports:
      - $REDIS_PORT:$REDIS_DOCKER_PORT
    restart: always

  postgres:
    container_name: cr-db
    image: postgres:18-alpine
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      PGDATA: /data/postgres
      TZ: $TIME_ZONE
    volumes:
      - /db/postgres:/data/postgres
    ports:
      - $DB_PORT:5432
    restart: always

volumes:
  db:
